### ISSUE TITLE
Seeming z-ording issue when running on Linux.

### ISSUE THREAD

**Issue by GIBson3** [vercidium-patreon/meshing#2]
When building/running on Linux there appears to be z-ordering issue where some further faces are are rendering on top of those that should be closer. Attached are a few screenshots.
![image](https://github.com/vercidium-patreon/meshing/assets/3137102/3119ab22-2ba6-47b1-bd22-4dc9d2f2a886)
![image](https://github.com/vercidium-patreon/meshing/assets/3137102/f0429b1b-e6be-40d8-a27b-fba7dd0b2648)

I did very quickly run against my windows box before filing this issue to verify that it was Linux specific. On Windows the renderer is reported as using Open GL 3.3, where as Linux reports Open GL 4.6 I don't know that that has any bearing on this, however I figured it didn't hurt to include. If I can provide any further information/Help let me know!

**Comment by Vercidium** [comment]
Thank you for the screenshots, it looks like it's rendering extra voxels over the top. 

Can you please also include a video panning up/down over the model like this?

https://github.com/vercidium-patreon/meshing/assets/12014138/635e9b6b-3a6a-4335-8a42-372d3a71a36a

> Edit: no need, I've reproduced it. Working on a fix now

**Comment by Vercidium** [comment]
This issue was related to depth testing. Silk.NET [doesn't create a depth buffer on the window by default on Linux](https://www.reddit.com/r/opengl/comments/z5c4ge/please_help_depth_testing_not_working/), so I've added an extra parameter when creating the window.

Can you please try again @GIBson3?

**Comment by GIBson3** [comment]
@Vercidium Looks great here! Thanks!
![image](https://github.com/vercidium-patreon/meshing/assets/3137102/2822ad77-a1ba-4cb1-9b1b-0fa22f7ed72c)
